Repository kyuridenamida/atcoder-tools, pull requests merged in 2021-04, with the labels that each got.

#221 Add a github workflow to autogenerate changelog
  .github/workflows/auto-generate-changelog.yml
  dev-tools/.gitignore
  dev-tools/package-lock.json
  dev-tools/package.json
  dev-tools/src/create-change-log.ts
  dev-tools/tsconfig.json
Labels: dev-env-improvement

#210 Remove redundant -0
  atcodertools/fmtprediction/models/calculator.py
  tests/resources/test_codegen/test_two_dimensional_case/cpp/generated_code.txt
  tests/resources/test_codegen/test_two_dimensional_case/cs/generated_code.txt
  tests/resources/test_codegen/test_two_dimensional_case/d/generated_code.txt
  tests/resources/test_codegen/test_two_dimensional_case/java/generated_code.txt
  tests/resources/test_codegen/test_two_dimensional_case/nim/generated_code.txt
  tests/resources/test_codegen/test_two_dimensional_case/python/generated_code.txt
  tests/resources/test_codegen/test_two_dimensional_case/rust/generated_code.txt
Labels: enhancement, generator

#217 Fix run_program crash on TLE test cases
  atcodertools/executils/run_program.py
Labels: bug

#223 Fix no inversion of save_no_session_cache in submit.py
  atcodertools/tools/submit.py
Labels: bug

#222 New option to skip preparing existing problem directories
  README.md
  atcodertools/config/config.py
  atcodertools/config/etc_config.py
  atcodertools/tools/atcodertools-default.toml
  atcodertools/tools/codegen.py
  atcodertools/tools/envgen.py
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/A/input_1.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/A/input_2.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/A/main.cpp
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/A/metadata.json
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/A/output_1.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/A/output_2.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/B/input_1.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/B/input_2.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/B/main.cpp
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/B/metadata.json
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/B/output_1.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/B/output_2.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/C/input_1.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/C/input_2.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/C/main.cpp
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/C/metadata.json
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/C/output_1.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/C/output_2.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/D/input_1.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/D/input_2.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/D/input_3.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/D/main.cpp
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/D/metadata.json
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/D/output_1.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/D/output_2.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/D/output_3.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/E/input_1.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/E/input_2.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/E/input_3.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/E/main.cpp
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/E/metadata.json
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/E/output_1.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/E/output_2.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/E/output_3.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/F/input_1.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/F/input_2.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/F/input_3.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/F/main.cpp
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/F/metadata.json
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/F/output_1.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/F/output_2.txt
  tests/resources/test_atc_env/test_skip_existing_problems/agc029/F/output_3.txt
  tests/test_envgen.py
Labels: enhancement

#211 Add Swift Support
  atcodertools/codegen/code_generators/swift.py
  atcodertools/common/language.py
  atcodertools/tools/templates/default_template.swift
  tests/resources/test_codegen/template.swift
  tests/resources/test_codegen/template_jinja.swift
  tests/resources/test_codegen/test_default_code_generators_and_templates/swift/echo_template.swift
  tests/resources/test_codegen/test_default_code_generators_and_templates/swift/expected_default_generated_code.swift
  tests/resources/test_codegen/test_default_code_generators_and_templates/swift/expected_echo_generated_code.swift
  tests/resources/test_codegen/test_float_case/swift/generated_code.txt
  tests/resources/test_codegen/test_long_case/swift/generated_code.txt
  tests/resources/test_codegen/test_mod_case/swift/generated_code.txt
  tests/resources/test_codegen/test_two_dimensional_case/swift/generated_code.txt
  tests/resources/test_codegen/test_yes_no_case/swift/generated_code.txt
  tests/test_codegen.py
Labels: enhancement, language-support
